---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - This project requires runners with specific tags to execute specific jobs
# - This project includes variables specific to using 'Docker In Docker'
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/bsk/bas-style-kit-file-upload-endpoint/settings/ci_cd

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensetive values are represented by "[Sensetive]"
#
# - Heroku
# > HEROKU_API_KEY: "[Sensetive]"

# == Global settings ==

stages:
  - package
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GITLAB_REGISTRY: docker-registry.data.bas.ac.uk
  APP_NAME: bas-style-kit-file-upload-endpoint
  HEROKU_APP_NAME: bas-style-kit-file-upload

# == Jobs ==

package-heroku:
  stage: package
  script:
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $GITLAB_REGISTRY"
    - "docker login -u _ -p $HEROKU_API_KEY registry.heroku.com"
    - "docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.heroku ."
    - "docker push registry.heroku.com/$HEROKU_APP_NAME/web"
  tags:
    - dnd
  only:
    - master

deploy-heroku:
  stage: deploy
  image:
    name: wingrunr21/alpine-heroku-cli
    entrypoint: [""]
  script:
    - "heroku container:release web --app $HEROKU_APP_NAME"
  only:
    - master