---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - This project requires runners with specific tags to execute specific jobs
# - This project includes variables specific to using 'Docker In Docker'
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/bsk/bas-style-kit-file-upload-endpoint/settings/ci_cd

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - Heroku
# > HEROKU_API_KEY: "[Sensitive]"
#
# - Snyk
# > SNYK_TOKEN: "[Sensitive]"

# == Global settings ==

stages:
  - test
  - package
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GITLAB_REGISTRY: docker-registry.data.bas.ac.uk
  APP_NAME: bas-style-kit-file-upload-endpoint
  HEROKU_APP_NAME: bas-style-kit-file-upload

image:
  name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-file-upload-endpoint:0.2.0-develop-alpine
  entrypoint: [""]

# == Jobs ==

test-app:
  stage: test
  script:
    - "flask test"

test-app-dependencies:
  stage: test
  image: snyk/snyk-cli:npm
  variables:
    PROJECT_FOLDER: "$CI_PROJECT_DIR"
  script:
    - "snyk test"

package-heroku:
  stage: package
  tags:
    - dnd
  services:
    - docker:dind
  image:
    name: docker:stable-dind
    entrypoint: [""]
  script:
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $GITLAB_REGISTRY"
    - "docker login -u _ -p $HEROKU_API_KEY registry.heroku.com"
    - "docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.heroku ."
    - "docker push registry.heroku.com/$HEROKU_APP_NAME/web"
  only:
    - master

deploy-heroku:
  stage: deploy
  image:
    name: wingrunr21/alpine-heroku-cli
    entrypoint: [""]
  script:
    - "heroku container:release web --app $HEROKU_APP_NAME"
  only:
    - master
