---
version: "2"

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-file-upload-endpoint:0.1.0-develop-alpine
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=9001
      - FLASK_ENV=development
    ports:
      - 9001:9001
