---
version: "2"

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-file-upload-endpoint:0.2.0-alpine
    command: flask run --host 0.0.0.0 --port 9001
    volumes:
      - .:/usr/src/app
    ports:
      - 9001:9001
